let headers = [
  {
    value: "DEL_NO",
    label: "Delivery Number",
    minWidth: "250px",
  },
  { value: "FKDAT", label: "Billing date" },
  // { value: "G5", label: "G5" },
  { value: "LGORT", label: "Storage Location" },
  { value: "WERKS", label: "Plant" },
  { value: "NAME1", label: "Plant Name", minWidth: "300px" },
  { value: "STCD3", label: "GSTIN" },
  { value: "VKORG", label: "Sales Organization" },
  { value: "VTWEG", label: "Distribution Channel" },
  {
    value: "VTEXT",
    label: "Distribution Channel Description",
    minWidth: "250px",
  },
  { value: "REGIO", label: "Region" },
  { value: "REGIO_TXT", label: "Region Description" },
  { value: "COUNC", label: "County Code" },
  { value: "BEZEI", label: "County Code Description", minWidth: "250px" },
  { value: "ZONE_DESC", label: "Zone" },
  { value: "FKIMG", label: "Actual Invoiced Quantity", minWidth: "250px" },
  { value: "ZZMDTRANS", label: "Mode of Transport" },
  { value: "DIST", label: "Distance" },
  { value: "JOCG", label: "CGST" },
  { value: "JOSG", label: "SGST" },
  { value: "JOIG", label: "IGST" },
  { value: "PRIM", label: "Primary FFW" },
  { value: "SEC", label: "Secondary FFW" },
  { value: "PRIMF", label: "Primary FEW" },
  { value: "SECF", label: "Secondary FEW" },
  { value: "Z1CD", label: "CD Discount" },
  { value: "Z1QD", label: "QD Discount" },
  { value: "GRO", label: "GRO" },
  { value: "FRT_AMT", label: "Rail Fright" },
  { value: "INCO1", label: "Incoterms (Part 1)" },
  {
    value: "NETWR",
    label: "Net Value in Document Currency",
    minWidth: "250px",
  },
  { value: "MWSBK", label: "Tax amount" },
  // { value: "BASEP", label: "Base Price" },
  // { value: "CST", label: "CST" },
  { value: "MRP", label: "MRP" },
  { value: "TCS", label: "TCS" },
  { value: "CITYC", label: "City Code" },
  { value: "CITY_DESC", label: "City Code Description", minWidth: "250px" },
  { value: "KUNAG", label: "Sold-to party" },
  { value: "BZTXT", label: "Sales Dist. Desc" },
  { value: "INV_NO", label: "Invoice Number" },
  { value: "CANCEL_INV", label: "Cancel Inv No" },
  { value: "CHALLAN", label: "Challan Number" },
  { value: "KTEXT", label: "CG" },
  { value: "CUST1_NAME1", label: "Sold to Party Name1", minWidth: "250px" },
  { value: "CUST1_NAME2", label: "Sold to Party Name2", minWidth: "250px" },
  { value: "KUNNR", label: "Customer Number", minWidth: "250px" },
  { value: "SP_COMM", label: "SP_COMM" },
  // { value: "ADD_VAT", label: "Additional Vat" },
  { value: "ERDAT", label: "Delivery Date" },
  { value: "G1", label: "G1" },
  { value: "ADD_CST", label: "Additional CST" },
  // { value: "SP_CODE", label: "SP_CODE" },
  { value: "CUST2_NAME1", label: "Ship to Party Name1", minWidth: "250px" },
  { value: "CUST2_NAME2", label: "Ship to Party Name2", minWidth: "250px" },
  { value: "UPCH", label: "Unload Ch" },
  // { value: "EX_INV", label: "EX_INV" },
  // {
  //   value: "EXNUM",
  //   label: "Official Excise Document Number",
  //   minWidth: "250px",
  // },
  { value: "CF_CODE", label: "C & F_CODE" },
  // { value: "GR_IR", label: "GR/LR No" },
  { value: "SGRP", label: "SGRP" },
  { value: "REF_DOC", label: "Ref_Doc No" },
  { value: "MATNR", label: "Material Number" },
  { value: "MAKTX", label: "Material Description", minWidth: "300px" },
  { value: "DELCDR", label: "DELCDR No" },
  // { value: "CANVAS", label: "Canvas Code" },
  { value: "SO_NO", label: "SOrder Number" },
  { value: "PROFORMA", label: "Proforma Number" },
  { value: "PGI_DT", label: "PGI Date" },
  { value: "CHAL_M", label: "Manual Challan No" },
  { value: "CHAL_DT", label: "Manual Challan Dt" },
  { value: "BWTAR", label: "Mfr plant" },
  // { value: "EX_DT", label: "Excise Date" },
  // { value: "EX_TIME", label: "Excise Time" },
  { value: "VKBUR", label: "Sales Office" },
  { value: "BSOTEXT", label: "Sales. Off. Desc" },
  { value: "SALES_GRP", label: "Sales Group" },
  { value: "SALES_GRP_DESC", label: "Sales Group Desc" },
  { value: "ZZLIFNR", label: "Forwarding Agent" },
  { value: "ZZSIGNI", label: "Truck Number" },
  // { value: "ZZBRGEW", label: "Gross Weight" },
  // { value: "ZZNTGEW", label: "Net Weight" },
  // { value: "ZZTTGEW", label: "Tare Weight" },
  { value: "ZZRPERMIT", label: "Road Permit" },
  { value: "J_1ICSTNO", label: "Central Sales Tax Number", minWidth: "250px" },
  { value: "J_1ILSTNO", label: "Local Sales Tax Number", minWidth: "250px" },
  { value: "J_1IPANNO", label: "Permanent Account Number", minWidth: "250px" },
  { value: "LZONE", label: "Transportation zone" },
  {
    value: "LZONE_TXT",
    label: "Transportation zone Description",
    minWidth: "250px",
  },
  { value: "ZTRANSP_NAME", label: "Transporter Name", minWidth: "300px" },
  { value: "DISTANCE", label: "Distance" },
  { value: "SEARCH", label: "search term" },
  { value: "AN_ID", label: "ArmannNirman Id" },
  { value: "EWAY_BILLNO", label: "E-Way Bill No" },
  { value: "SHP_CCD", label: "SHP County" },
  { value: "SHP_CCD_DES", label: "SHP County Des." },
  { value: "SALES_PROMO", label: "Sales Promoter" },
  { value: "SP_NAME", label: "Sales Promoter Name", minWidth: "250px" },
  { value: "SHP_TYP", label: "Shipping type" },
  { value: "C_ZZSHIP1", label: "Diversion Ship to 1", minWidth: "250px" },
  { value: "C_NAME1", label: "Customer Name1", minWidth: "250px" },
  { value: "C_ZZQTY1", label: "Quantity" },
  { value: "C_ZZSHIP2", label: "Diversion Ship to 2", minWidth: "250px" },
  { value: "C_NAME2", label: "Customer Name2", minWidth: "250px" },
  { value: "C_ZZQTY2", label: "Quantity" },
  { value: "C_ZZSHIP3", label: "Diversion Ship to 3", minWidth: "250px" },
  { value: "C_NAME3", label: "Customer Name3", minWidth: "250px" },
  { value: "C_ZZQTY3", label: "Quantity" },
  { value: "ERROR_MSG", label: "Einv_Error", minWidth: "500px" },
  { value: "SHIPMENT_NO", label: "Shipment Number", minWidth: "250px" },
  { value: "SHIP_COST_NO", label: "Shipment Cost Number", minWidth: "250px" },
  { value: "GR_NO", label: "GR Number", minWidth: "250px" },
];

export default headers;
